### ISSUE TITLE
Review use if IPv4 addresses

### ISSUE THREAD

**Issue by lladdy** [aiarena/general#30]
Do we need them?
How many can we reduce?
Do we only need one for the load balancer, or multiple - per web worker?

IPv6 an option?

**Comment by ipeterov** [comment]
It's not easy to disable ipv4 addresses - [currently the containers need them](https://stackoverflow.com/questions/61265108/aws-ecs-fargate-resourceinitializationerror-unable-to-pull-secrets-or-registry) to connect to the docker registry, and for internet access in general.

It's possible to launch everything in a private subnet, and set up a NAT gateway in it for internet access, so if we really want to get rid of the ipv4 charges, that's what we'll have to do.
